# -*- coding: utf-8 -*-
"""imp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWRVJ4Ql3KWOwrN6Z1AedsMA-wBr0H49
"""

import pandas as pd
from sklearn.utils import resample

# load original
df = pd.read_csv("/content/drive/MyDrive/fer2013.csv")

print("Before balancing:")
print(df["emotion"].value_counts())

# split majority & minority by group
groups = df.groupby("emotion")

# find largest class count
max_count = groups.size().max()

# oversample each class to match largest count
balanced_df = pd.concat([
    grp if len(grp) == max_count else resample(grp,
                                               replace=True,
                                               n_samples=max_count,
                                               random_state=42)
    for _, grp in groups
])

print("\nAfter balancing:")
print(balanced_df["emotion"].value_counts())

# save new csv
balanced_df.to_csv("fer2013_balanced.csv", index=False)
print("\nBalanced dataset saved as fer2013_balanced.csv")